version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.7-node
    steps:
      - checkout
      # - restore_cache:
      #     key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      # - save_cache:
      #     key: composer-v1-{{ checksum "composer.lock" }}
      #     paths:
      #       - vendor
      # - restore_cache:
      #     key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: |
            if [ ! -d node_modules ]; then
              npm install
            fi
      # - save_cache:
      #     key: npm-v1-{{ checksum "package-lock.json" }}
      #     paths:
      #       - node_modules
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
